#include "../../headers/types.h"

state_t *getCurrExceptionState();

/* Handles only processor's local timer interrupts*/
void pltInterruptHandler();

/* Handles only interval timer interrupts generated by a pseudo-clock tick*/
void itInterruptHandler();

/* Handles all the interrupts that aren't generated through timers*/
void deviceInterruptHandler();

/* Main function, used to handle interrupt exceptions which calls the previously
 * declared functions*/
void interruptHandler();
